services:
  loader:
    image: mateusememe/rinha2026-c:v8
    platform: linux/amd64
    command: ["/bin/bash", "/app/start.sh", "loader"]
    volumes:
      - data:/app/data
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 200M

  api1:
    image: mateusememe/rinha2026-c:v8
    platform: linux/amd64
    command: ["/bin/bash", "/app/start.sh"]
    environment:
      - PORT=9001
    volumes:
      - data:/app/data
    depends_on:
      loader:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/ready"]
      interval: 3s
      timeout: 2s
      retries: 20
      start_period: 2s
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 65M

  api2:
    image: mateusememe/rinha2026-c:v8
    platform: linux/amd64
    command: ["/bin/bash", "/app/start.sh"]
    environment:
      - PORT=9002
    volumes:
      - data:/app/data
    depends_on:
      loader:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9002/ready"]
      interval: 3s
      timeout: 2s
      retries: 20
      start_period: 2s
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 65M

  lb:
    image: nginx:alpine
    platform: linux/amd64
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      api1:
        condition: service_healthy
      api2:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 20M

volumes:
  data:
