version: '3.8'
services:
  loader:
    build: .
    command: ["/bin/bash", "/app/start.sh", "loader"]
    volumes:
      - data:/app/data
      - ../:/dataset_up:ro
      - .:/dataset_here:ro
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 150M

  api1:
    build: .
    command: ["/bin/bash", "/app/start.sh"]
    environment:
      - PORT=9001
    volumes:
      - data:/app/data
    depends_on:
      loader:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 90M

  api2:
    build: .
    command: ["/bin/bash", "/app/start.sh"]
    environment:
      - PORT=9002
    volumes:
      - data:/app/data
    depends_on:
      loader:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 90M

  lb:
    build: .
    command: ["/usr/local/bin/lb", "9999", "api1:9001", "api2:9002"]
    ports:
      - "9999:9999"
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 20M

volumes:
  data:
