services:
  loader:
    image: mateusememe/rinha2026-c:v13
    platform: linux/amd64
    command: ["/bin/bash", "/app/start.sh", "loader"]
    volumes:
      - data:/app/data
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 200M

  api1:
    image: mateusememe/rinha2026-c:v13
    platform: linux/amd64
    command: ["/bin/bash", "/app/start.sh"]
    environment:
      - API_SOCKET=/sockets/api1.sock
    volumes:
      - data:/app/data
      - sockets:/sockets
    depends_on:
      loader:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 65M

  api2:
    image: mateusememe/rinha2026-c:v13
    platform: linux/amd64
    command: ["/bin/bash", "/app/start.sh"]
    environment:
      - API_SOCKET=/sockets/api2.sock
    volumes:
      - data:/app/data
      - sockets:/sockets
    depends_on:
      loader:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 65M

  lb:
    image: mateusememe/rinha2026-c:v13
    platform: linux/amd64
    command: ["/bin/bash", "/app/start.sh", "lb"]
    environment:
      - API1_SOCKET=/sockets/api1.sock
      - API2_SOCKET=/sockets/api2.sock
    volumes:
      - sockets:/sockets
    ports:
      - "9999:9999"
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 20M

volumes:
  data:
  sockets:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=4m,uid=0,gid=0,mode=0777"
